import { QorusService } from '@qoretechnologies/ts-toolkit';

export const MockServicesData = [
  {
    autostart: true,
    enabled: true,
    loaded: '2023-10-03T12:00:00Z',
    name: 'Enabled_Service',
    display_name: 'Enabled Service',
    serviceid: 1,
    type: 'user',
    version: '1.0',
    manual_autostart: false,
    methods: [],
    remote: false,
    stateless: false,
    status: 'whatever',
  },
  {
    autostart: false,
    enabled: false,
    name: 'Disabled_Service',
    display_name: 'Disabled Service',
    serviceid: 2,
    type: 'user',
    version: '1.0',
    manual_autostart: false,
    methods: [],
    remote: false,
    stateless: false,
    status: 'whatever',
  },
  {
    autostart: false,
    enabled: false,
    name: 'service_3',
    alerts: [
      {
        alert: 'alert_1',
        alertid: 1,
        alerttype: 'ONGOING',
        id: 3,
        instance: 'mock_instance',
        local: false,
        name: 'Alert 1',
        object: 'service_3',
        reason: 'This is a test',
        source: 'service_3',
        type: 'SERVICE',
        when: '2023-10-03T12:00:00Z',
        who: 'mock_user',
      },
    ],
    display_name: 'Service With Alerts',
    serviceid: 3,
    type: 'user',
    version: '1.0',
    manual_autostart: false,
    methods: [],
    remote: false,
    stateless: false,
    status: 'whatever',
  },
  {
    autostart: false,
    enabled: true,
    name: 'service_4',
    display_name: 'Service With No Alerts',
    serviceid: 4,
    type: 'user',
    version: '1.0',
    manual_autostart: false,
    methods: [],
    remote: true,
    stateless: false,
    status: 'whatever',
  },
  {
    autostart: true,
    enabled: true,
    name: 'service_5',
    display_name: 'System Service',
    serviceid: 5,
    type: 'system',
    version: '1.0',
    manual_autostart: false,
    methods: [],
    stateless: false,
    status: 'whatever',
  },
] as QorusService[];
