import { ReqoreP, ReqoreSpinner, ReqoreTree } from '@qoretechnologies/reqore';
import { StoryObj } from '@storybook/react';
import { testsWaitForText } from '../../../__tests__/utils';
import { StoryMeta } from '../../types';
import { currentUserStore } from './currentUser';

const meta = {
  title: 'Stores/Current User',
  render: () => {
    const { load, loading, currentUser = {}, errorData } = currentUserStore();

    return loading ? (
      <ReqoreSpinner />
    ) : (
      <>
        <ReqoreTree
          data={errorData || currentUser}
          bottomActions={[{ label: 'Refetch', onClick: load }]}
        />
      </>
    );
  },
} as StoryMeta<any>;

export default meta;
export type Story = StoryObj<typeof meta>;

export const currentUserCanBeLoaded: Story = {
  parameters: {
    mockData: [
      {
        // An array of mock objects which will add in every story
        url: 'https://hq.qoretechnologies.com:8092/api/latest/users?action=current',
        method: 'GET',
        status: 200,
        delay: 200,
        response: {
          provider: 'ldap(ldap://hq.qoretechnologies.com:389, dc=qoretechnologies,dc=com)',
          username: 'fwitosz',
          name: 'Filip Witosz',
          has_default: true,
          roles: ['posixAccount'],
          permissions: [
            'SHUTDOWN',
            'WORKFLOW-CONTROL',
            'SERVICE-CONTROL',
            'EDIT-WORKFLOW-DATA',
            'CALL-USER-SERVICES-RW',
            'CALL-SYSTEM-SERVICES-RW',
            'USER-CONTROL',
            'OPTION-CONTROL',
            'SUBMIT-ORDER',
            'LOGGER-CONTROL',
            'EXEC-SYNC-WORKFLOW',
            'DATASOURCE-CONTROL',
            'GROUP-CONTROL',
            'SERVER-CONTROL',
            'JOB-CONTROL',
            'SCHEMA-CONTROL',
            'USER-CONNECTION-CONTROL',
            'LOGIN',
            'FILESYSTEM-CONTROL',
            'SERVER-CONNECTION-CONTROL',
            'MAPPER-CONTROL',
            'VALUE-MAP-CONTROL',
            'SENSITIVE-DATA-CONTROL',
            'SLA-CONTROL',
            'DEBUG-CONTROL',
            'REMOTE-DEPLOYMENT',
            'REMOTE-DELETE-INTERFACE',
            'REMOTE-RELEASE',
            'KILL-PROCESS',
            'DATA-PROVIDER-CONTROL',
            'TYPE-CACHE-CONTROL',
            'SET-FSM-CONFIG',
            'SET-PIPELINE-CONFIG',
            'UPLOAD',
            'REMOTE-EXEC-ALL',
            'WEBDAV-CONTROL',
            'SCALING',
            'CREATOR-CONTROL',
          ],
          workflows: [],
          services: [],
          jobs: [],
          mappers: [],
          vmaps: [],
          fsms: [],
          pipelines: [],
          groups: ['DEFAULT'],
          storage: {
            jobs: {
              paneSize: 400,
              sort: {
                sortBy: 'id',
                sortByKey: {
                  direction: 1,
                  ignoreCase: true,
                },
                historySortBy: 'last_executed',
                historySortByKey: {
                  direction: 1,
                  ignoreCase: true,
                },
              },
            },
            connections: {
              paneSize: 776,
            },
            locale: 'en-US',
            theme: 'dark',
            hideCodeByDefault: true,
            services: {
              paneSize: 1240,
              sort: {
                sortBy: 'id',
                sortByKey: {
                  direction: -1,
                  ignoreCase: true,
                },
                historySortBy: 'desc',
                historySortByKey: {
                  direction: -1,
                  ignoreCase: true,
                },
              },
              searches: ['khgkjh'],
            },
            notifications: {
              paneSize: 779,
            },
            ongoing: {
              sort: {
                sortBy: 'name',
                sortByKey: {
                  direction: -1,
                  ignoreCase: true,
                },
                historySortBy: 'when',
                historySortByKey: {
                  ignoreCase: true,
                  direction: -1,
                },
              },
            },
            slas: {
              sort: {
                sortBy: 'name',
                sortByKey: {
                  direction: -1,
                  ignoreCase: true,
                },
                historySortBy: 'slaid',
                historySortByKey: {
                  ignoreCase: true,
                  direction: -1,
                },
              },
            },
            methods: {
              sort: {
                sortBy: 'name',
                sortByKey: {
                  direction: -1,
                  ignoreCase: true,
                },
              },
            },
            ide: {
              sidebarColor: '#0c797d',
              headerColor: '#b0bc00',
              isDarkTheme: true,
              config: {
                autoSaveDraft: {
                  type: 'boolean',
                  value: true,
                },
                allowAiCreateDialog: {
                  type: 'boolean',
                  value: true,
                },
              },
              qog: {
                'pane-size': -131,
              },
              appCatalogueFavorites: ['Discord', 'GoogleCalendar', 'Hubspot', 'OpenAI'],
              qogFirstVisit: false,
              settings: {
                qogs: {
                  '128': {},
                },
              },
            },
            favoriteMenuItems: ['ocmd', 'search', 'search', 'ocmd', 'search', 'search'],
            alerts: {
              paneSize: 733,
            },
            valuemaps: {
              paneSize: 1415,
            },
            settings: {
              notificationsEnabled: false,
              notificationsSound: true,
              dashboardModules: [
                'orderStats',
                'interfaces',
                'connections',
                'cluster',
                'overview',
                'remotes',
                'nodeData',
              ],
              notificationsBrowser: false,
            },
            configItems: {
              searches: ['list'],
            },
            sidebarOpen: true,
            workflows: {
              paneSize: 1081,
              sort: {
                sortBy: 'COMPLETE',
                sortByKey: {
                  direction: -1,
                  ignoreCase: true,
                },
                historySortBy: 'INCOMPLETE',
                historySortByKey: {
                  direction: -1,
                  ignoreCase: true,
                },
              },
              searches: ['erp batch '],
            },
            user: {
              sort: {
                sortBy: 'name',
                sortByKey: {
                  direction: -1,
                  ignoreCase: true,
                },
              },
            },
            orders: {
              sort: {
                sortBy: 'name',
                sortByKey: {
                  direction: 1,
                  ignoreCase: true,
                },
                historySortBy: 'workflowstatus',
                historySortByKey: {
                  direction: 1,
                  ignoreCase: true,
                },
              },
            },
            vscode: {
              dataProviderFavorites: {
                ivCn8dVg4: {
                  name: 'Hash',
                  desc: '',
                  value: {
                    type: 'type',
                    name: 'qore',
                    can_manage_fields: true,
                    descriptions: ['type entry group', 'Qore data type "hash<auto>"'],
                    path: '/hash',
                    searchOptionsChanged: false,
                  },
                  record: {},
                  id: 'ivCn8dVg4',
                },
                '0FpPkIdD8': {
                  name: '',
                  desc: '',
                  value: {
                    type: 'type',
                    name: 'qore',
                    can_manage_fields: false,
                    descriptions: [
                      'type entry group',
                      'type entry group',
                      'Qore data type "hash<auto>"',
                      'type entry group',
                      'type entry group',
                      'Qore data type "hash<auto>"',
                      'Qore data type "int"',
                    ],
                    path: '/fsevents/event/action',
                    searchOptionsChanged: false,
                  },
                  record: {},
                  id: '0FpPkIdD8',
                },
              },
            },
          },
          oauth2_clients: [
            {
              client_id: 'uitest',
              client_description: 'missing',
              username: 'fwitosz',
              created: '2022-10-03T10:06:17.018364+02:00',
              modified: '2022-10-03T10:06:17.018364+02:00',
              permissions: [
                'SHUTDOWN',
                'WORKFLOW-CONTROL',
                'SERVICE-CONTROL',
                'EDIT-WORKFLOW-DATA',
                'CALL-USER-SERVICES-RW',
                'CALL-SYSTEM-SERVICES-RW',
                'USER-CONTROL',
                'OPTION-CONTROL',
                'SUBMIT-ORDER',
                'LOGGER-CONTROL',
                'EXEC-SYNC-WORKFLOW',
                'DATASOURCE-CONTROL',
                'GROUP-CONTROL',
                'SERVER-CONTROL',
                'JOB-CONTROL',
                'SCHEMA-CONTROL',
                'USER-CONNECTION-CONTROL',
                'LOGIN',
                'FILESYSTEM-CONTROL',
                'SERVER-CONNECTION-CONTROL',
                'MAPPER-CONTROL',
                'VALUE-MAP-CONTROL',
                'SENSITIVE-DATA-CONTROL',
                'SLA-CONTROL',
                'DEBUG-CONTROL',
                'REMOTE-DEPLOYMENT',
                'REMOTE-DELETE-INTERFACE',
                'REMOTE-RELEASE',
                'KILL-PROCESS',
                'DATA-PROVIDER-CONTROL',
                'TYPE-CACHE-CONTROL',
                'SET-FSM-CONFIG',
                'SET-PIPELINE-CONFIG',
                'UPLOAD',
                'REMOTE-EXEC-ALL',
                'WEBDAV-CONTROL',
                'SCALING',
                'CREATOR-CONTROL',
              ],
            },
            {
              client_id: '0e5649a2-49c9-4582-90fe-5ba120d86495',
              client_description: 'Test',
              username: 'fwitosz',
              created: '2024-02-01T09:41:32.949242+01:00',
              modified: '2024-02-01T09:41:32.949242+01:00',
              permissions: [
                'SHUTDOWN',
                'WORKFLOW-CONTROL',
                'SERVICE-CONTROL',
                'EDIT-WORKFLOW-DATA',
                'CALL-USER-SERVICES-RW',
                'CALL-SYSTEM-SERVICES-RW',
                'USER-CONTROL',
                'OPTION-CONTROL',
                'SUBMIT-ORDER',
                'LOGGER-CONTROL',
                'EXEC-SYNC-WORKFLOW',
                'DATASOURCE-CONTROL',
                'GROUP-CONTROL',
                'SERVER-CONTROL',
                'JOB-CONTROL',
                'SCHEMA-CONTROL',
                'USER-CONNECTION-CONTROL',
                'LOGIN',
                'FILESYSTEM-CONTROL',
                'SERVER-CONNECTION-CONTROL',
                'MAPPER-CONTROL',
                'VALUE-MAP-CONTROL',
                'SENSITIVE-DATA-CONTROL',
                'SLA-CONTROL',
                'DEBUG-CONTROL',
                'REMOTE-DEPLOYMENT',
                'REMOTE-DELETE-INTERFACE',
                'REMOTE-RELEASE',
                'KILL-PROCESS',
                'DATA-PROVIDER-CONTROL',
                'TYPE-CACHE-CONTROL',
                'SET-FSM-CONFIG',
                'SET-PIPELINE-CONFIG',
                'UPLOAD',
                'REMOTE-EXEC-ALL',
                'WEBDAV-CONTROL',
                'SCALING',
                'CREATOR-CONTROL',
              ],
            },
            {
              client_id: 'e451c692-9b02-4e02-81e9-aaedbc417f95',
              client_description: 'asgasg',
              username: 'fwitosz',
              created: '2024-02-01T13:40:50.063262+01:00',
              modified: '2024-02-01T13:40:50.063262+01:00',
              permissions: ['CALL-SYSTEM-SERVICES-RW'],
            },
            {
              client_id: '15b25f29-598f-43f2-8253-e3937bcdfd25',
              client_description: 'qweqweqweqwe',
              username: 'fwitosz',
              created: '2024-02-01T13:42:28.711432+01:00',
              modified: '2024-02-01T13:42:28.711432+01:00',
              permissions: [
                'SHUTDOWN',
                'WORKFLOW-CONTROL',
                'SERVICE-CONTROL',
                'EDIT-WORKFLOW-DATA',
                'CALL-USER-SERVICES-RW',
                'CALL-SYSTEM-SERVICES-RW',
                'USER-CONTROL',
                'OPTION-CONTROL',
                'SUBMIT-ORDER',
                'LOGGER-CONTROL',
                'EXEC-SYNC-WORKFLOW',
                'DATASOURCE-CONTROL',
                'GROUP-CONTROL',
                'SERVER-CONTROL',
                'JOB-CONTROL',
                'SCHEMA-CONTROL',
                'USER-CONNECTION-CONTROL',
                'LOGIN',
                'FILESYSTEM-CONTROL',
                'SERVER-CONNECTION-CONTROL',
                'MAPPER-CONTROL',
                'VALUE-MAP-CONTROL',
                'SENSITIVE-DATA-CONTROL',
                'SLA-CONTROL',
                'DEBUG-CONTROL',
                'REMOTE-DEPLOYMENT',
                'REMOTE-DELETE-INTERFACE',
                'REMOTE-RELEASE',
                'KILL-PROCESS',
                'DATA-PROVIDER-CONTROL',
                'TYPE-CACHE-CONTROL',
                'SET-FSM-CONFIG',
                'SET-PIPELINE-CONFIG',
                'UPLOAD',
                'REMOTE-EXEC-ALL',
                'WEBDAV-CONTROL',
                'SCALING',
                'CREATOR-CONTROL',
              ],
            },
            {
              client_id: '23e8b0ac-e1f5-4040-ae88-86d6da788834',
              client_description: '123asg',
              username: 'fwitosz',
              created: '2024-02-01T13:45:35.765626+01:00',
              modified: '2024-02-01T13:45:35.765626+01:00',
              permissions: [
                'SHUTDOWN',
                'WORKFLOW-CONTROL',
                'SERVICE-CONTROL',
                'EDIT-WORKFLOW-DATA',
                'CALL-USER-SERVICES-RW',
                'CALL-SYSTEM-SERVICES-RW',
                'USER-CONTROL',
                'OPTION-CONTROL',
                'SUBMIT-ORDER',
                'LOGGER-CONTROL',
                'EXEC-SYNC-WORKFLOW',
                'DATASOURCE-CONTROL',
                'GROUP-CONTROL',
                'SERVER-CONTROL',
                'JOB-CONTROL',
                'SCHEMA-CONTROL',
                'USER-CONNECTION-CONTROL',
                'LOGIN',
                'FILESYSTEM-CONTROL',
                'SERVER-CONNECTION-CONTROL',
                'MAPPER-CONTROL',
                'VALUE-MAP-CONTROL',
                'SENSITIVE-DATA-CONTROL',
                'SLA-CONTROL',
                'DEBUG-CONTROL',
                'REMOTE-DEPLOYMENT',
                'REMOTE-DELETE-INTERFACE',
                'REMOTE-RELEASE',
                'KILL-PROCESS',
                'DATA-PROVIDER-CONTROL',
                'TYPE-CACHE-CONTROL',
                'SET-FSM-CONFIG',
                'SET-PIPELINE-CONFIG',
                'UPLOAD',
                'REMOTE-EXEC-ALL',
                'WEBDAV-CONTROL',
                'SCALING',
                'CREATOR-CONTROL',
              ],
            },
            {
              client_id: '746ff82a-22b1-4da5-8631-05e120f46738',
              client_description: 'Empty test',
              username: 'fwitosz',
              created: '2023-08-22T12:19:18.867345+02:00',
              modified: '2023-08-23T11:01:41.237892+02:00',
              permissions: [
                'SHUTDOWN',
                'WORKFLOW-CONTROL',
                'SERVICE-CONTROL',
                'EDIT-WORKFLOW-DATA',
                'CALL-USER-SERVICES-RW',
                'CALL-SYSTEM-SERVICES-RW',
                'USER-CONTROL',
                'OPTION-CONTROL',
                'SUBMIT-ORDER',
                'LOGGER-CONTROL',
                'EXEC-SYNC-WORKFLOW',
                'DATASOURCE-CONTROL',
                'GROUP-CONTROL',
                'SERVER-CONTROL',
                'JOB-CONTROL',
                'SCHEMA-CONTROL',
                'USER-CONNECTION-CONTROL',
                'LOGIN',
                'FILESYSTEM-CONTROL',
                'SERVER-CONNECTION-CONTROL',
                'MAPPER-CONTROL',
                'VALUE-MAP-CONTROL',
                'SENSITIVE-DATA-CONTROL',
                'SLA-CONTROL',
                'DEBUG-CONTROL',
                'REMOTE-DEPLOYMENT',
                'REMOTE-DELETE-INTERFACE',
                'REMOTE-RELEASE',
                'KILL-PROCESS',
                'DATA-PROVIDER-CONTROL',
                'TYPE-CACHE-CONTROL',
                'SET-FSM-CONFIG',
                'SET-PIPELINE-CONFIG',
                'UPLOAD',
                'REMOTE-EXEC-ALL',
                'WEBDAV-CONTROL',
                'SCALING',
                'CREATOR-CONTROL',
              ],
            },
            {
              client_id: '3eb35389-825d-4646-987f-b2db5d2a7e87',
              client_description: 'New test',
              username: 'fwitosz',
              created: '2023-08-22T11:26:14.781407+02:00',
              modified: '2023-08-22T14:19:41.037535+02:00',
              permissions: [],
            },
            {
              client_id: '5ffe0255-3104-4352-b8d0-4b339347a418',
              client_description: 'Test',
              username: 'fwitosz',
              created: '2022-12-08T11:08:38.154825+01:00',
              modified: '2022-12-08T11:08:55.691055+01:00',
              permissions: [
                'SHUTDOWN',
                'WORKFLOW-CONTROL',
                'SERVICE-CONTROL',
                'EDIT-WORKFLOW-DATA',
                'CALL-USER-SERVICES-RW',
                'CALL-SYSTEM-SERVICES-RW',
                'USER-CONTROL',
                'OPTION-CONTROL',
                'SUBMIT-ORDER',
                'LOGGER-CONTROL',
                'EXEC-SYNC-WORKFLOW',
                'DATASOURCE-CONTROL',
                'GROUP-CONTROL',
                'SERVER-CONTROL',
                'JOB-CONTROL',
                'SCHEMA-CONTROL',
                'USER-CONNECTION-CONTROL',
                'LOGIN',
                'FILESYSTEM-CONTROL',
                'SERVER-CONNECTION-CONTROL',
                'MAPPER-CONTROL',
                'VALUE-MAP-CONTROL',
                'SENSITIVE-DATA-CONTROL',
                'SLA-CONTROL',
                'DEBUG-CONTROL',
                'REMOTE-DEPLOYMENT',
                'REMOTE-DELETE-INTERFACE',
                'REMOTE-RELEASE',
                'KILL-PROCESS',
                'DATA-PROVIDER-CONTROL',
                'TYPE-CACHE-CONTROL',
                'SET-FSM-CONFIG',
                'SET-PIPELINE-CONFIG',
                'UPLOAD',
                'REMOTE-EXEC-ALL',
                'WEBDAV-CONTROL',
                'SCALING',
                'CREATOR-CONTROL',
              ],
            },
          ],
        },
      },
    ],
  },
  play: async () => {
    await testsWaitForText('"Filip Witosz"');
  },
};

export const currentUserCanNotBeLoaded: Story = {
  play: async () => {
    await testsWaitForText('"GET-USER-ERROR"');
  },
};

export const currentUserHasPermissions: Story = {
  ...currentUserCanBeLoaded,
  render: () => {
    const { hasPermissions } = currentUserStore();

    return (
      <ReqoreP>
        {hasPermissions(['SERVER-CONTROL']) ? 'Yes, user has "SERVER-CONTROL" permission' : 'No'}
      </ReqoreP>
    );
  },
  play: async () => {
    await testsWaitForText('Yes, user has "SERVER-CONTROL" permission');
  },
};
