export const SERVICES_API_URL = 'services/';
export const SERVICES_ACTIONS_PERMISSIONS = {
  toggleEnabled: ['SERVICE-CONTROL', 'GROUP-CONTROL', 'MODIFY-GROUP', 'MODIFY-GROUP-STATUS'],
  toggleAutostart: ['SERVICE-CONTROL', 'SET-SERVICE-AUTOSTART'],
  load: [
    'CALL-SYSTEM-SERVICES-RW',
    'CALL-SYSTEM-SERVICES-RO',
    'CALL-USER-SERVICES-RW',
    'CALL-USER-SERVICES-RO',
  ],
  unload: ['SERVICE-CONTROL', 'UNLOAD-SERVICE'],
  setRemote: ['SERVICE-CONTROL'],
  reset: ['SERVICE-CONTROL', 'RESET-SERVICE'],
  manageSystemService: ['SERVER-CONTROL', 'SYSTEM-SERVICE-CONTROL'],
};
